### ISSUE TITLE
Get to the special characters on Windows platform

### ISSUE THREAD

**Issue by Wyatex** [BestBurning/platform_device_id#33]
Getting a UUID on the Windows platform gets the newline character.
```
D:\MyData\xxxxx>wmic csproduct get uuid
UUID
5D1DC14B-754E-4797-AFEA-4237AA0F7018


D:\MyData\xxxxx>
```
So I will get the string contains ` \r\n\r\n`. This causes the program to run incorrectly, so can the library handle the problem？

**Comment by ceeyang** [comment]
![image](https://user-images.githubusercontent.com/16550007/218245261-c9d1d501-4ef9-4324-b375-66d306de260b.png)
I have to same problem.

**Comment by Wyatex** [comment]
I guess you have to deal with it yourself. The author should no longer maintain this project.

**Comment by ceeyang** [comment]
> 

Thanks very much, I had used the another package.

**Comment by connerjson** [comment]
> > 
> 
> Thanks very much, I had used the another package.

which package are you using now.

**Comment by ceeyang** [comment]
> > > 
> > 
> > 
> > Thanks very much, I had used the another package.
> 
> which package are you using now.

[device_info_plus](https://pub.dev/packages/device_info_plus)
