### ISSUE TITLE
Native Linux and Windows

### ISSUE THREAD

**Issue by mjafartp** [BestBurning/platform_device_id#8]
Add support to native Linux and windows

**Comment by BestBurning** [comment]
It's support native Linux and windows from [v1.0.1](https://pub.dev/packages/platform_device_id/versions/1.0.1)

**Comment by Hu-Wentao** [comment]
Can't work under pure dart (dart native)

**Comment by timothyao** [comment]
This package should be able to work in pure Dart with little modification.
